"""Compliance Report Generation.

Generates regulatory compliance reports including Consumer Confidence
Reports (CCR), monthly operating reports, and sampling summaries.

Supports both standard EPA formats and state-specific templates.
"""

from datetime import date, datetime
from enum import Enum
from typing import Any

from pydantic import BaseModel, Field


class ReportType(str, Enum):
    """Types of compliance reports."""

    CCR = "CCR"  # Consumer Confidence Report
    MOR = "MOR"  # Monthly Operating Report
    SAMPLING = "SAMPLING"  # Sampling Summary
    VIOLATION = "VIOLATION"  # Violation Response


class ReportSection(BaseModel):
    """A section within a compliance report."""

    title: str = Field(..., description="Section title")
    content: str = Field(..., description="Section content")
    data_tables: list[dict[str, Any]] = Field(
        default_factory=list, description="Data tables in section"
    )


class ComplianceReport(BaseModel):
    """Generated compliance report."""

    report_id: str = Field(..., description="Unique report identifier")
    report_type: ReportType = Field(..., description="Type of report")
    title: str = Field(..., description="Report title")

    # Period
    period_start: date = Field(..., description="Report period start")
    period_end: date = Field(..., description="Report period end")

    # Generation metadata
    generated_at: datetime = Field(
        default_factory=datetime.now, description="When generated"
    )
    generated_by: str = Field(default="system", description="Generated by")

    # Content
    sections: list[ReportSection] = Field(
        default_factory=list, description="Report sections"
    )

    # Summary
    compliance_status: str = Field(
        ..., description="Overall compliance status"
    )
    violations_count: int = Field(
        default=0, description="Number of violations in period"
    )

    # Output
    format: str = Field(default="pdf", description="Output format")


def generate_report(
    report_type: ReportType,
    period_start: date,
    period_end: date,
    include_supporting_data: bool = True,
) -> ComplianceReport:
    """
    Generate a compliance report.

    Args:
        report_type: Type of report to generate
        period_start: Report period start date
        period_end: Report period end date
        include_supporting_data: Include detailed data tables

    Returns:
        Generated ComplianceReport
    """
    report_id = f"{report_type.value}-{datetime.now().strftime('%Y%m%d%H%M%S')}"

    if report_type == ReportType.CCR:
        return _generate_ccr(report_id, period_start, period_end, include_supporting_data)
    elif report_type == ReportType.MOR:
        return _generate_mor(report_id, period_start, period_end, include_supporting_data)
    elif report_type == ReportType.SAMPLING:
        return _generate_sampling_report(
            report_id, period_start, period_end, include_supporting_data
        )
    else:
        return _generate_violation_report(
            report_id, period_start, period_end, include_supporting_data
        )


def _generate_ccr(
    report_id: str,
    period_start: date,
    period_end: date,
    include_data: bool,
) -> ComplianceReport:
    """Generate Consumer Confidence Report."""
    sections = [
        ReportSection(
            title="Introduction",
            content=(
                "This report contains important information about your drinking water. "
                "Please read it carefully. Este informe contiene información muy "
                "importante sobre su agua potable. Tradúzcalo o hable con alguien "
                "que lo entienda bien."
            ),
            data_tables=[],
        ),
        ReportSection(
            title="Water Source Information",
            content=(
                "Your water comes from [SOURCE TYPE] sources. "
                "Our water supply includes [NUMBER] active wells drawing from "
                "the [AQUIFER NAME] aquifer."
            ),
            data_tables=[],
        ),
        ReportSection(
            title="Detected Contaminants",
            content="The following contaminants were detected during the reporting period:",
            data_tables=[
                {
                    "headers": ["Contaminant", "MCL", "Range", "Average", "Violation"],
                    "rows": [
                        ["Total Coliform", "0", "0-0", "0", "No"],
                        ["Chlorine Residual", "4.0 mg/L", "0.5-1.2", "0.8", "No"],
                        ["Nitrate", "10 mg/L", "1.2-2.5", "1.8", "No"],
                    ],
                }
            ]
            if include_data
            else [],
        ),
        ReportSection(
            title="Compliance Summary",
            content=(
                "During the reporting period, we met all drinking water "
                "health standards. We are committed to providing you with "
                "quality drinking water."
            ),
            data_tables=[],
        ),
    ]

    return ComplianceReport(
        report_id=report_id,
        report_type=ReportType.CCR,
        title=f"Consumer Confidence Report {period_start.year}",
        period_start=period_start,
        period_end=period_end,
        sections=sections,
        compliance_status="compliant",
        violations_count=0,
    )


def _generate_mor(
    report_id: str,
    period_start: date,
    period_end: date,
    include_data: bool,
) -> ComplianceReport:
    """Generate Monthly Operating Report."""
    sections = [
        ReportSection(
            title="Production Summary",
            content="Monthly water production and distribution summary.",
            data_tables=[
                {
                    "headers": ["Metric", "Value", "Unit"],
                    "rows": [
                        ["Total Production", "5,250,000", "gallons"],
                        ["Peak Day Production", "210,000", "gallons"],
                        ["Average Daily Production", "175,000", "gallons"],
                        ["Total Connections Served", "850", "connections"],
                    ],
                }
            ]
            if include_data
            else [],
        ),
        ReportSection(
            title="Treatment Operations",
            content="Summary of treatment operations and chemical usage.",
            data_tables=[
                {
                    "headers": ["Chemical", "Usage", "Unit", "Avg Dose"],
                    "rows": [
                        ["Chlorine", "125", "lbs", "1.2 mg/L"],
                        ["Fluoride", "45", "lbs", "0.7 mg/L"],
                    ],
                }
            ]
            if include_data
            else [],
        ),
        ReportSection(
            title="Water Quality Monitoring",
            content="Summary of water quality monitoring results.",
            data_tables=[
                {
                    "headers": ["Parameter", "Samples", "Range", "Average"],
                    "rows": [
                        ["Chlorine Residual", "62", "0.5-1.5 mg/L", "0.9 mg/L"],
                        ["Turbidity", "31", "0.1-0.4 NTU", "0.2 NTU"],
                        ["pH", "31", "7.2-7.8", "7.5"],
                    ],
                }
            ]
            if include_data
            else [],
        ),
    ]

    return ComplianceReport(
        report_id=report_id,
        report_type=ReportType.MOR,
        title=f"Monthly Operating Report - {period_start.strftime('%B %Y')}",
        period_start=period_start,
        period_end=period_end,
        sections=sections,
        compliance_status="compliant",
        violations_count=0,
    )


def _generate_sampling_report(
    report_id: str,
    period_start: date,
    period_end: date,
    include_data: bool,
) -> ComplianceReport:
    """Generate Sampling Summary Report."""
    sections = [
        ReportSection(
            title="Sampling Summary",
            content="Summary of water quality samples collected during the reporting period.",
            data_tables=[
                {
                    "headers": [
                        "Sample Type",
                        "Required",
                        "Collected",
                        "Compliant",
                        "Status",
                    ],
                    "rows": [
                        ["Total Coliform", "4", "4", "4", "Complete"],
                        ["Chlorine Residual", "62", "62", "62", "Complete"],
                        ["DBP (TTHM/HAA5)", "1", "1", "1", "Complete"],
                    ],
                }
            ]
            if include_data
            else [],
        ),
    ]

    return ComplianceReport(
        report_id=report_id,
        report_type=ReportType.SAMPLING,
        title=f"Sampling Summary - {period_start.strftime('%B %Y')}",
        period_start=period_start,
        period_end=period_end,
        sections=sections,
        compliance_status="compliant",
        violations_count=0,
    )


def _generate_violation_report(
    report_id: str,
    period_start: date,
    period_end: date,
    include_data: bool,
) -> ComplianceReport:
    """Generate Violation Response Report."""
    sections = [
        ReportSection(
            title="Violation Description",
            content="[Placeholder for violation description]",
            data_tables=[],
        ),
        ReportSection(
            title="Root Cause Analysis",
            content="[Placeholder for root cause analysis]",
            data_tables=[],
        ),
        ReportSection(
            title="Corrective Actions",
            content="[Placeholder for corrective actions taken]",
            data_tables=[],
        ),
        ReportSection(
            title="Prevention Measures",
            content="[Placeholder for measures to prevent recurrence]",
            data_tables=[],
        ),
    ]

    return ComplianceReport(
        report_id=report_id,
        report_type=ReportType.VIOLATION,
        title="Violation Response Report",
        period_start=period_start,
        period_end=period_end,
        sections=sections,
        compliance_status="non-compliant",
        violations_count=1,
    )

